### ISSUE TITLE
No Usable Connection On T-Mobile Germany

### ISSUE THREAD

**Issue by LotP** [WhisperSystems/RedPhone#375] opened 2015-02-13 19:31 UTC
Don't know if RedPhone's still in development, but I submit this issue right away.

If a customer of the DTAG (Deutsche Telekom AG) is called or is calling another RedPhone user, the first 2 seconds sound perfectly fine, after that a few seconds roboter voice (no communication possible) and the connection quality's further decreasing down to some stuttering noise.

It is reported that DTAG blocks VoIP-services (ZRTP / SRTP / SIP) on their networks making encrypted communication impossible.

Possible solution: change port and wrap traffic so it can't be censored that easy.

**Comment by moxie0** [comment] 2015-02-13 21:23
Duplicate of #322

**Closed by moxie0** 2015-02-13 21:23 UTC
